stocks = [
    "HDFCAMC.NS",
    "HDFCBANK.NS",
    "HDFCLIFE.NS",
    "HFCL.NS",
    "HAVELLS.NS",
    "HEROMOTOCO.NS",
    "HEXT.NS",
    "HSCL.NS",
    "HINDALCO.NS",
    "HAL.NS",
    "HINDCOPPER.NS",
    "HINDPETRO.NS",
    "HINDUNILVR.NS",
    "HINDZINC.NS",
    "POWERINDIA.NS",
    "HOMEFIRST.NS",
    "HONASA.NS",
    "HONAUT.NS",
    "HUDCO.NS",
    "HYUNDAI.NS",
    "ICICIBANK.NS",
    "ICICIGI.NS",
    "ICICIAMC.NS"

]
