sector_map = {

    "ARE&M.NS": "Automobile and Auto Components",
    "APOLLOTYRE.NS": "Automobile and Auto Components",
    "ASAHIINDIA.NS": "Automobile and Auto Components",
    "ATHERENERG.NS": "Automobile and Auto Components",
    "BAJAJ-AUTO.NS": "Automobile and Auto Components",
    "BALKRISIND.NS": "Automobile and Auto Components",
    "BELRISE.NS": "Automobile and Auto Components",
    "BHARATFORG.NS": "Automobile and Auto Components",
    "BOSCHLTD.NS": "Automobile and Auto Components",
    "CIEINDIA.NS": "Automobile and Auto Components",
    "CEATLTD.NS": "Automobile and Auto Components",
    "CRAFTSMAN.NS": "Automobile and Auto Components",
    "EICHERMOT.NS": "Automobile and Auto Components",
    "ENDURANCE.NS": "Automobile and Auto Components",
    "EXIDEIND.NS": "Automobile and Auto Components",
    "FORCEMOT.NS": "Automobile and Auto Components",
    "GABRIEL.NS": "Automobile and Auto Components",
    "HEROMOTOCO.NS": "Automobile and Auto Components",
    "HYUNDAI.NS": "Automobile and Auto Components",
    "JBMA.NS": "Automobile and Auto Components",
    "JKTYRE.NS": "Automobile and Auto Components",
    "MRF.NS": "Automobile and Auto Components",
    "M&M.NS": "Automobile and Auto Components",
    "MARUTI.NS": "Automobile and Auto Components",
    "MINDACORP.NS": "Automobile and Auto Components",
    "MSUMI.NS": "Automobile and Auto Components",
    "OLAELEC.NS": "Automobile and Auto Components",
    "OLECTRA.NS": "Automobile and Auto Components",
    "RKFORGE.NS": "Automobile and Auto Components",
    "MOTHERSON.NS": "Automobile and Auto Components",
    "SCHAEFFLER.NS": "Automobile and Auto Components",
    "SONACOMS.NS": "Automobile and Auto Components",
    "TVSMOTOR.NS": "Automobile and Auto Components",
    "TMPV.NS": "Automobile and Auto Components",
    "TENNIND.NS": "Automobile and Auto Components",
    "TIINDIA.NS": "Automobile and Auto Components",
    "UNOMINDA.NS": "Automobile and Auto Components",
    "ZFCVINDIA.NS": "Automobile and Auto Components",
    "ABB.NS": "Capital Goods",
    "AIAENG.NS": "Capital Goods",
    "APLAPOLLO.NS": "Capital Goods",
    "ACE.NS": "Capital Goods",
    "CPPLUS.NS": "Capital Goods",
    "APARINDS.NS": "Capital Goods",
    "ASHOKLEY.NS": "Capital Goods",
    "ASTRAL.NS": "Capital Goods",
    "BEML.NS": "Capital Goods",
    "BDL.NS": "Capital Goods",
    "BEL.NS": "Capital Goods",
    "BHEL.NS": "Capital Goods",
    "CGPOWER.NS": "Capital Goods",
    "CARBORUNIV.NS": "Capital Goods",
    "COCHINSHIP.NS": "Capital Goods",
    "CUMMINSIND.NS": "Capital Goods",
    "DATAPATTNS.NS": "Capital Goods",
    "ELECON.NS": "Capital Goods",
    "ELGIEQUIP.NS": "Capital Goods",
    "EMMVEE.NS": "Capital Goods",
    "ESCORTS.NS": "Capital Goods",
    "FINCABLES.NS": "Capital Goods",
    "GVT&D.NS": "Capital Goods",
    "GALLANTT.NS": "Capital Goods",
    "GRSE.NS": "Capital Goods",
    "GPIL.NS": "Capital Goods",
    "GRAPHITE.NS": "Capital Goods",
    "HEG.NS": "Capital Goods",
    "HBLENGINE.NS": "Capital Goods",
    "HAL.NS": "Capital Goods",
    "POWERINDIA.NS": "Capital Goods",
    "HONAUT.NS": "Capital Goods",
    "INOXWIND.NS": "Capital Goods",
    "JINDALSAW.NS": "Capital Goods",
    "JWL.NS": "Capital Goods",
    "JYOTICNC.NS": "Capital Goods",
    "KEI.NS": "Capital Goods",
    "KAYNES.NS": "Capital Goods",
    "KIRLOSENG.NS": "Capital Goods",
    "MAZDOCK.NS": "Capital Goods",
    "PTCIL.NS": "Capital Goods",
    "POLYCAB.NS": "Capital Goods",
    "PREMIERENE.NS": "Capital Goods",
    "RRKABEL.NS": "Capital Goods",
    "RHIM.NS": "Capital Goods",
    "SCHNEIDER.NS": "Capital Goods",
    "SHYAMMETL.NS": "Capital Goods",
    "ENRIN.NS": "Capital Goods",
    "SIEMENS.NS": "Capital Goods",
    "SUPREMEIND.NS": "Capital Goods",
    "SUZLON.NS": "Capital Goods",
    "SYRMA.NS": "Capital Goods",
    "TMCV.NS": "Capital Goods",
    "TEGA.NS": "Capital Goods",
    "THERMAX.NS": "Capital Goods",
    "TIMKEN.NS": "Capital Goods",
    "TITAGARH.NS": "Capital Goods",
    "TARIL.NS": "Capital Goods",
    "TRITURBINE.NS": "Capital Goods",
    "USHAMART.NS": "Capital Goods",
    "WAAREEENER.NS": "Capital Goods",
    "WELCORP.NS": "Capital Goods",
    "ZENTEC.NS": "Capital Goods",
    "AARTIIND.NS": "Chemicals",
    "ANURAS.NS": "Chemicals",
    "ATUL.NS": "Chemicals",
    "BAYERCROP.NS": "Chemicals",
    "CHAMBLFERT.NS": "Chemicals",
    "CLEAN.NS": "Chemicals",
    "COROMANDEL.NS": "Chemicals",
    "DEEPAKFERT.NS": "Chemicals",
    "DEEPAKNTR.NS": "Chemicals",
    "FACT.NS": "Chemicals",
    "FLUOROCHEM.NS": "Chemicals",
    "HSCL.NS": "Chemicals",
    "JUBLINGREA.NS": "Chemicals",
    "LINDEINDIA.NS": "Chemicals",
    "NAVINFLUOR.NS": "Chemicals",
    "PCBL.NS": "Chemicals",
    "PIIND.NS": "Chemicals",
    "PARADEEP.NS": "Chemicals",
    "PIDILITIND.NS": "Chemicals",
    "SRF.NS": "Chemicals",
    "SOLARINDS.NS": "Chemicals",
    "SUMICHEM.NS": "Chemicals",
    "SPLPETRO.NS": "Chemicals",
    "SWANCORP.NS": "Chemicals",
    "TATACHEM.NS": "Chemicals",
    "UPL.NS": "Chemicals",
    "AFCONS.NS": "Construction",
    "CEMPRO.NS": "Construction",
    "ENGINERSIN.NS": "Construction",
    "IRB.NS": "Construction",
    "IRCON.NS": "Construction",
    "KPIL.NS": "Construction",
    "KEC.NS": "Construction",
    "LT.NS": "Construction",
    "NBCC.NS": "Construction",
    "NCC.NS": "Construction",
    "RITES.NS": "Construction",
    "RVNL.NS": "Construction",
    "TECHNOE.NS": "Construction",
    "ACC.NS": "Construction Materials",
    "AMBUJACEM.NS": "Construction Materials",
    "DALBHARAT.NS": "Construction Materials",
    "GRASIM.NS": "Construction Materials",
    "INDIACEM.NS": "Construction Materials",
    "JKCEMENT.NS": "Construction Materials",
    "JSWCEMENT.NS": "Construction Materials",
    "NUVOCO.NS": "Construction Materials",
    "SHREECEM.NS": "Construction Materials",
    "RAMCOCEM.NS": "Construction Materials",
    "ULTRACEMCO.NS": "Construction Materials",
    "AMBER.NS": "Consumer Durables",
    "ASIANPAINT.NS": "Consumer Durables",
    "BATAINDIA.NS": "Consumer Durables",
    "BERGEPAINT.NS": "Consumer Durables",
    "BLUESTARCO.NS": "Consumer Durables",
    "CROMPTON.NS": "Consumer Durables",
    "DIXON.NS": "Consumer Durables",
    "HAVELLS.NS": "Consumer Durables",
    "JSWDULUX.NS": "Consumer Durables",
    "KAJARIACER.NS": "Consumer Durables",
    "KALYANKJIL.NS": "Consumer Durables",
    "LGEINDIA.NS": "Consumer Durables",
    "PGEL.NS": "Consumer Durables",
    "TITAN.NS": "Consumer Durables",
    "VOLTAS.NS": "Consumer Durables",
    "WHIRLPOOL.NS": "Consumer Durables",
    "ABFRL.NS": "Consumer Services",
    "ABLBL.NS": "Consumer Services",
    "DMART.NS": "Consumer Services",
    "BLS.NS": "Consumer Services",
    "FIRSTCRY.NS": "Consumer Services",
    "CARTRADE.NS": "Consumer Services",
    "CHALET.NS": "Consumer Services",
    "DEVYANI.NS": "Consumer Services",
    "EIHOTEL.NS": "Consumer Services",
    "ETERNAL.NS": "Consumer Services",
    "NYKAA.NS": "Consumer Services",
    "ITCHOTELS.NS": "Consumer Services",
    "INDIAMART.NS": "Consumer Services",
    "INDHOTEL.NS": "Consumer Services",
    "IRCTC.NS": "Consumer Services",
    "NAUKRI.NS": "Consumer Services",
    "JUBLFOOD.NS": "Consumer Services",
    "THELEELA.NS": "Consumer Services",
    "LEMONTREE.NS": "Consumer Services",
    "LENSKART.NS": "Consumer Services",
    "MEESHO.NS": "Consumer Services",
    "PWL.NS": "Consumer Services",
    "SAPPHIRE.NS": "Consumer Services",
    "SWIGGY.NS": "Consumer Services",
    "TBOTEK.NS": "Consumer Services",
    "TRAVELFOOD.NS": "Consumer Services",
    "TRENT.NS": "Consumer Services",
    "URBANCO.NS": "Consumer Services",
    "VMM.NS": "Consumer Services",
    "3MINDIA.NS": "Diversified",
    "DCMSHRIRAM.NS": "Diversified",
    "GODREJIND.NS": "Diversified",
    "AWL.NS": "Fast Moving Consumer Goods",
    "ABDL.NS": "Fast Moving Consumer Goods",
    "BALRAMCHIN.NS": "Fast Moving Consumer Goods",
    "BIKAJI.NS": "Fast Moving Consumer Goods",
    "BBTC.NS": "Fast Moving Consumer Goods",
    "BRITANNIA.NS": "Fast Moving Consumer Goods",
    "CCL.NS": "Fast Moving Consumer Goods",
    "COLPAL.NS": "Fast Moving Consumer Goods",
    "DOMS.NS": "Fast Moving Consumer Goods",
    "DABUR.NS": "Fast Moving Consumer Goods",
    "EIDPARRY.NS": "Fast Moving Consumer Goods",
    "EMAMILTD.NS": "Fast Moving Consumer Goods",
    "GILLETTE.NS": "Fast Moving Consumer Goods",
    "GODFRYPHLP.NS": "Fast Moving Consumer Goods",
    "GODREJCP.NS": "Fast Moving Consumer Goods",
    "HINDUNILVR.NS": "Fast Moving Consumer Goods",
    "HONASA.NS": "Fast Moving Consumer Goods",
    "ITC.NS": "Fast Moving Consumer Goods",
    "LTFOODS.NS": "Fast Moving Consumer Goods",
    "MARICO.NS": "Fast Moving Consumer Goods",
    "NESTLEIND.NS": "Fast Moving Consumer Goods",
    "PATANJALI.NS": "Fast Moving Consumer Goods",
    "RADICO.NS": "Fast Moving Consumer Goods",
    "TATACONSUM.NS": "Fast Moving Consumer Goods",
    "UBL.NS": "Fast Moving Consumer Goods",
    "UNITDSPR.NS": "Fast Moving Consumer Goods",
    "VBL.NS": "Fast Moving Consumer Goods",
    "ZYDUSWELL.NS": "Fast Moving Consumer Goods",
    "360ONE.NS": "Financial Services",
    "AUBANK.NS": "Financial Services",
    "AADHARHFC.NS": "Financial Services",
    "AAVAS.NS": "Financial Services",
    "ABCAPITAL.NS": "Financial Services",
    "ABSLAMC.NS": "Financial Services",
    "ANANDRATHI.NS": "Financial Services",
    "ANGELONE.NS": "Financial Services",
    "APTUS.NS": "Financial Services",
    "AIIL.NS": "Financial Services",
    "AXISBANK.NS": "Financial Services",
    "BSE.NS": "Financial Services",
    "BAJFINANCE.NS": "Financial Services",
    "BAJAJFINSV.NS": "Financial Services",
    "BAJAJHLDNG.NS": "Financial Services",
    "BAJAJHFL.NS": "Financial Services",
    "BANDHANBNK.NS": "Financial Services",
    "BANKBARODA.NS": "Financial Services",
    "BANKINDIA.NS": "Financial Services",
    "MAHABANK.NS": "Financial Services",
    "GROWW.NS": "Financial Services",
    "CRISIL.NS": "Financial Services",
    "CANFINHOME.NS": "Financial Services",
    "CANBK.NS": "Financial Services",
    "CANHLIFE.NS": "Financial Services",
    "CGCL.NS": "Financial Services",
    "CENTRALBK.NS": "Financial Services",
    "CDSL.NS": "Financial Services",
    "CHOICEIN.NS": "Financial Services",
    "CHOLAHLDNG.NS": "Financial Services",
    "CHOLAFIN.NS": "Financial Services",
    "CUB.NS": "Financial Services",
    "CAMS.NS": "Financial Services",
    "CREDITACC.NS": "Financial Services",
    "FEDERALBNK.NS": "Financial Services",
    "FIVESTAR.NS": "Financial Services",
    "GICRE.NS": "Financial Services",
    "GODIGIT.NS": "Financial Services",
    "HDBFS.NS": "Financial Services",
    "HDFCAMC.NS": "Financial Services",
    "HDFCBANK.NS": "Financial Services",
    "HDFCLIFE.NS": "Financial Services",
    "HOMEFIRST.NS": "Financial Services",
    "HUDCO.NS": "Financial Services",
    "ICICIBANK.NS": "Financial Services",
    "ICICIGI.NS": "Financial Services",
    "ICICIAMC.NS": "Financial Services",
    "ICICIPRULI.NS": "Financial Services",
    "IDBI.NS": "Financial Services",
    "IDFCFIRSTB.NS": "Financial Services",
    "IFCI.NS": "Financial Services",
    "IIFL.NS": "Financial Services",
    "INDIANB.NS": "Financial Services",
    "IEX.NS": "Financial Services",
    "IOB.NS": "Financial Services",
    "IRFC.NS": "Financial Services",
    "IREDA.NS": "Financial Services",
    "INDUSINDBK.NS": "Financial Services",
    "JMFINANCIL.NS": "Financial Services",
    "J&KBANK.NS": "Financial Services",
    "JIOFIN.NS": "Financial Services",
    "KARURVYSYA.NS": "Financial Services",
    "KFINTECH.NS": "Financial Services",
    "KOTAKBANK.NS": "Financial Services",
    "LTF.NS": "Financial Services",
    "LICHSGFIN.NS": "Financial Services",
    "LICI.NS": "Financial Services",
    "M&MFIN.NS": "Financial Services",
    "MANAPPURAM.NS": "Financial Services",
    "MFSL.NS": "Financial Services",
    "MOTILALOFS.NS": "Financial Services",
    "MCX.NS": "Financial Services",
    "MUTHOOTFIN.NS": "Financial Services",
    "NAM-INDIA.NS": "Financial Services",
    "NIVABUPA.NS": "Financial Services",
    "NUVAMA.NS": "Financial Services",
    "PAYTM.NS": "Financial Services",
    "POLICYBZR.NS": "Financial Services",
    "PNBHOUSING.NS": "Financial Services",
    "PINELABS.NS": "Financial Services",
    "PIRAMALFIN.NS": "Financial Services",
    "POONAWALLA.NS": "Financial Services",
    "PFC.NS": "Financial Services",
    "PNB.NS": "Financial Services",
    "RBLBANK.NS": "Financial Services",
    "RECLTD.NS": "Financial Services",
    "SBFC.NS": "Financial Services",
    "SBICARD.NS": "Financial Services",
    "SBILIFE.NS": "Financial Services",
    "SAMMAANCAP.NS": "Financial Services",
    "SHRIRAMFIN.NS": "Financial Services",
    "STARHEALTH.NS": "Financial Services",
    "SBIN.NS": "Financial Services",
    "SUNDARMFIN.NS": "Financial Services",
    "TATACAP.NS": "Financial Services",
    "TATAINVEST.NS": "Financial Services",
    "NIACL.NS": "Financial Services",
    "UCOBANK.NS": "Financial Services",
    "UTIAMC.NS": "Financial Services",
    "UNIONBANK.NS": "Financial Services",
    "YESBANK.NS": "Financial Services",
    "ABBOTINDIA.NS": "Healthcare",
    "ACUTAAS.NS": "Healthcare",
    "AJANTPHARM.NS": "Healthcare",
    "ALKEM.NS": "Healthcare",
    "ANTHEM.NS": "Healthcare",
    "APOLLOHOSP.NS": "Healthcare",
    "ASTERDM.NS": "Healthcare",
    "AUROPHARMA.NS": "Healthcare",
    "BIOCON.NS": "Healthcare",
    "BLUEJET.NS": "Healthcare",
    "CAPLIPOINT.NS": "Healthcare",
    "CIPLA.NS": "Healthcare",
    "COHANCE.NS": "Healthcare",
    "CONCORDBIO.NS": "Healthcare",
    "DIVISLAB.NS": "Healthcare",
    "LALPATHLAB.NS": "Healthcare",
    "DRREDDY.NS": "Healthcare",
    "EMCURE.NS": "Healthcare",
    "ERIS.NS": "Healthcare",
    "FORTIS.NS": "Healthcare",
    "GLAND.NS": "Healthcare",
    "GLAXO.NS": "Healthcare",
    "GLENMARK.NS": "Healthcare",
    "MEDANTA.NS": "Healthcare",
    "GRANULES.NS": "Healthcare",
    "INDGN.NS": "Healthcare",
    "IPCALAB.NS": "Healthcare",
    "JBCHEPHARM.NS": "Healthcare",
    "JUBLPHARMA.NS": "Healthcare",
    "KIMS.NS": "Healthcare",
    "LAURUSLABS.NS": "Healthcare",
    "LUPIN.NS": "Healthcare",
    "MANKIND.NS": "Healthcare",
    "MAXHEALTH.NS": "Healthcare",
    "NATCOPHARM.NS": "Healthcare",
    "NH.NS": "Healthcare",
    "NEULANDLAB.NS": "Healthcare",
    "ONESOURCE.NS": "Healthcare",
    "PFIZER.NS": "Healthcare",
    "PPLPHARMA.NS": "Healthcare",
    "POLYMED.NS": "Healthcare",
    "RAINBOW.NS": "Healthcare",
    "SAILIFE.NS": "Healthcare",
    "SUNPHARMA.NS": "Healthcare",
    "SYNGENE.NS": "Healthcare",
    "TORNTPHARM.NS": "Healthcare",
    "VIJAYA.NS": "Healthcare",
    "WOCKPHARMA.NS": "Healthcare",
    "ZYDUSLIFE.NS": "Healthcare",
    "AFFLE.NS": "Information Technology",
    "BSOFT.NS": "Information Technology",
    "MAPMYINDIA.NS": "Information Technology",
    "COFORGE.NS": "Information Technology",
    "CYIENT.NS": "Information Technology",
    "HCLTECH.NS": "Information Technology",
    "HEXT.NS": "Information Technology",
    "INFY.NS": "Information Technology",
    "INTELLECT.NS": "Information Technology",
    "IKS.NS": "Information Technology",
    "KPITTECH.NS": "Information Technology",
    "LTTS.NS": "Information Technology",
    "LTM.NS": "Information Technology",
    "LATENTVIEW.NS": "Information Technology",
    "MPHASIS.NS": "Information Technology",
    "NETWEB.NS": "Information Technology",
    "NEWGEN.NS": "Information Technology",
    "OFSS.NS": "Information Technology",
    "PERSISTENT.NS": "Information Technology",
    "SAGILITY.NS": "Information Technology",
    "SONATSOFTW.NS": "Information Technology",
    "TCS.NS": "Information Technology",
    "TATAELXSI.NS": "Information Technology",
    "TATATECH.NS": "Information Technology",
    "TECHM.NS": "Information Technology",
    "WIPRO.NS": "Information Technology",
    "ZENSARTECH.NS": "Information Technology",
    "PVRINOX.NS": "Media Entertainment & Publication",
    "SAREGAMA.NS": "Media Entertainment & Publication",
    "SUNTV.NS": "Media Entertainment & Publication",
    "ZEEL.NS": "Media Entertainment & Publication",
    "ADANIENT.NS": "Metals & Mining",
    "DUMMYVEDL1.NS": "Metals & Mining",
    "DUMMYVEDL4.NS": "Metals & Mining",
    "GRAVITA.NS": "Metals & Mining",
    "GMDCLTD.NS": "Metals & Mining",
    "HINDALCO.NS": "Metals & Mining",
    "HINDCOPPER.NS": "Metals & Mining",
    "HINDZINC.NS": "Metals & Mining",
    "JSWSTEEL.NS": "Metals & Mining",
    "JAINREC.NS": "Metals & Mining",
    "JSL.NS": "Metals & Mining",
    "JINDALSTEL.NS": "Metals & Mining",
    "LLOYDSME.NS": "Metals & Mining",
    "NMDC.NS": "Metals & Mining",
    "NSLNISP.NS": "Metals & Mining",
    "NATIONALUM.NS": "Metals & Mining",
    "SARDAEN.NS": "Metals & Mining",
    "SAIL.NS": "Metals & Mining",
    "TATASTEEL.NS": "Metals & Mining",
    "VEDL.NS": "Metals & Mining",
    "ATGL.NS": "Oil Gas & Consumable Fuels",
    "AEGISLOG.NS": "Oil Gas & Consumable Fuels",
    "AEGISVOPAK.NS": "Oil Gas & Consumable Fuels",
    "BPCL.NS": "Oil Gas & Consumable Fuels",
    "CASTROLIND.NS": "Oil Gas & Consumable Fuels",
    "CHENNPETRO.NS": "Oil Gas & Consumable Fuels",
    "COALINDIA.NS": "Oil Gas & Consumable Fuels",
    "DUMMYVEDL3.NS": "Oil Gas & Consumable Fuels",
    "GAIL.NS": "Oil Gas & Consumable Fuels",
    "HINDPETRO.NS": "Oil Gas & Consumable Fuels",
    "IOC.NS": "Oil Gas & Consumable Fuels",
    "IGL.NS": "Oil Gas & Consumable Fuels",
    "MGL.NS": "Oil Gas & Consumable Fuels",
    "MRPL.NS": "Oil Gas & Consumable Fuels",
    "ONGC.NS": "Oil Gas & Consumable Fuels",
    "OIL.NS": "Oil Gas & Consumable Fuels",
    "PETRONET.NS": "Oil Gas & Consumable Fuels",
    "RELIANCE.NS": "Oil Gas & Consumable Fuels",
    "ACMESOLAR.NS": "Power",
    "ADANIENSOL.NS": "Power",
    "ADANIGREEN.NS": "Power",
    "ADANIPOWER.NS": "Power",
    "CESC.NS": "Power",
    "DUMMYVEDL2.NS": "Power",
    "JSWENERGY.NS": "Power",
    "JPPOWER.NS": "Power",
    "NHPC.NS": "Power",
    "NLCINDIA.NS": "Power",
    "NTPCGREEN.NS": "Power",
    "NTPC.NS": "Power",
    "NAVA.NS": "Power",
    "POWERGRID.NS": "Power",
    "RPOWER.NS": "Power",
    "SJVN.NS": "Power",
    "TATAPOWER.NS": "Power",
    "TORNTPOWER.NS": "Power",
    "ABREL.NS": "Realty",
    "ANANTRAJ.NS": "Realty",
    "BRIGADE.NS": "Realty",
    "DLF.NS": "Realty",
    "GODREJPROP.NS": "Realty",
    "LODHA.NS": "Realty",
    "OBEROIRLTY.NS": "Realty",
    "PHOENIXLTD.NS": "Realty",
    "PRESTIGE.NS": "Realty",
    "SIGNATURE.NS": "Realty",
    "SOBHA.NS": "Realty",
    "ADANIPORTS.NS": "Services",
    "BLUEDART.NS": "Services",
    "CONCOR.NS": "Services",
    "DELHIVERY.NS": "Services",
    "FSL.NS": "Services",
    "GMRAIRPORT.NS": "Services",
    "GESHIP.NS": "Services",
    "INDIGO.NS": "Services",
    "IGIL.NS": "Services",
    "JSWINFRA.NS": "Services",
    "MMTC.NS": "Services",
    "REDINGTON.NS": "Services",
    "SCI.NS": "Services",
    "ECLERX.NS": "Services",
    "BHARTIARTL.NS": "Telecommunication",
    "BHARTIHEXA.NS": "Telecommunication",
    "HFCL.NS": "Telecommunication",
    "ITI.NS": "Telecommunication",
    "INDUSTOWER.NS": "Telecommunication",
    "RAILTEL.NS": "Telecommunication",
    "TATACOMM.NS": "Telecommunication",
    "TTML.NS": "Telecommunication",
    "TEJASNET.NS": "Telecommunication",
    "IDEA.NS": "Telecommunication",
    "KPRMILL.NS": "Textiles",
    "PAGEIND.NS": "Textiles",
    "TRIDENT.NS": "Textiles",
    "VTL.NS": "Textiles",
    "WELSPUNLIV.NS": "Textiles",
    "AARTIPHARM.NS": "Healthcare",
    "AEQUS.NS": "Capital Goods",
    "ALOKINDS.NS": "Textiles",
    "ANUP.NS": "Capital Goods",
    "APOLLO.NS": "Automobile and Auto Components",
    "ASHAPURMIN.NS": "Metals & Mining",
    "ASTRAMICRO.NS": "Capital Goods",
    "ASTRAZEN.NS": "Healthcare",
    "AVANTIFEED.NS": "Fast Moving Consumer Goods",
    "BAJAJELEC.NS": "Consumer Durables",
    "BALAMINES.NS": "Chemicals",
    "BALUFORGE.NS": "Capital Goods",
    "BANCOINDIA.NS": "Automobile and Auto Components",
    "BBOX.NS": "Construction",
    "BECTORFOOD.NS": "Fast Moving Consumer Goods",
    "BLACKBUCK.NS": "Information Technology",
    "BLUESTONE.NS": "Consumer Durables",
    "BORORENEW.NS": "Capital Goods",
    "CCAVENUE.NS": "Financial Services",
    "CELLO.NS": "Consumer Durables",
    "CSBBANK.NS": "Financial Services",
    "CUPID.NS": "Healthcare",
    "DIACABS.NS": "Capital Goods",
    "ELECTCAST.NS": "Diversified",
    "EMBDL.NS": "Fast Moving Consumer Goods",
    "GHCL.NS": "Chemicals",
    "GMMPFAUDLR.NS": "Capital Goods",
    "GNFC.NS": "Chemicals",
    "GOKEX.NS": "Services",
    "GPPL.NS": "Services",
    "GRWRHITECH.NS": "Diversified",
    "GSFC.NS": "Chemicals",
    "GUJGASLTD.NS": "Oil Gas & Consumable Fuels",
    "HAPPSTMNDS.NS": "Information Technology",
    "HCC.NS": "Construction",
    "IFBIND.NS": "Consumer Durables",
    "INDIGOPNTS.NS": "Consumer Durables",
    "INOXGREEN.NS": "Services",
    "JAMNAAUTO.NS": "Automobile and Auto Components",
    "JSLL.NS": "Metals & Mining",
    "JSWHL.NS": "Financial Services",
    "KRBL.NS": "Fast Moving Consumer Goods",
    "KTKBANK.NS": "Financial Services",
    "LUMAXTECH.NS": "Automobile and Auto Components",
    "MARKSANS.NS": "Healthcare",
    "METROPOLIS.NS": "Healthcare",
    "MIDHANI.NS": "Metals & Mining",
    "MTARTECH.NS": "Capital Goods",
    "NETWORK18.NS": "Media Entertainment & Publication",
    "OSWALPUMPS.NS": "Capital Goods",
    "PARAS.NS": "Capital Goods",
    "PCJEWELLER.NS": "Consumer Durables",
    "PGHH.NS": "Fast Moving Consumer Goods",
    "PNGJL.NS": "Consumer Durables",
    "PRAJIND.NS": "Capital Goods",
    "PRSMJOHNSN.NS": "Construction Materials",
    "RAIN.NS": "Chemicals",
    "RATEGAIN.NS": "Information Technology",
    "RAYMONDLSL.NS": "Textiles",
    "REFEX.NS": "Oil Gas & Consumable Fuels",
    "RELAXO.NS": "Consumer Durables",
    "RENUKA.NS": "Fast Moving Consumer Goods",
    "RTNPOWER.NS": "Power",
    "SANSERA.NS": "Automobile and Auto Components",
    "SHAILY.NS": "Diversified",
    "SHAKTIPUMP.NS": "Capital Goods",
    "SHARDACROP.NS": "Chemicals",
    "SHRIPISTON.NS": "Automobile and Auto Components",
    "SKFINDUS.NS": "Capital Goods",
    "SKIPPER.NS": "Capital Goods",
    "SPARC.NS": "Healthcare",
    "SUNTECK.NS": "Realty",
    "SUPRIYA.NS": "Healthcare",
    "SURYAROSNI.NS": "Capital Goods",
    "SWSOLAR.NS": "Capital Goods",
    "TANLA.NS": "Information Technology",
    "TDPOWERSYS.NS": "Capital Goods",
    "THANGAMAYL.NS": "Consumer Durables",
    "THOMASCOOK.NS": "Consumer Services",
    "TI.NS": "Automobile and Auto Components",
    "TIMETECHNO.NS": "Consumer Durables",
    "TRANSRAILL.NS": "Capital Goods",
    "UJJIVANSFB.NS": "Financial Services",
    "V2RETAIL.NS": "Consumer Services",
    "VARROC.NS": "Automobile and Auto Components",
    "VIKRAMSOLR.NS": "Capital Goods",
    "VIPIND.NS": "Consumer Durables",
    "VIYASH.NS": "Healthcare",
    "VOLTAMP.NS": "Capital Goods",
    "WABAG.NS": "Construction",


}

